// @ts-check
import { themes as prismThemes } from 'prism-react-renderer';

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Personal AI Infrastructure Docs',
  tagline: 'Auto-generated documentation for Daniel Miessler\'s Personal AI Infrastructure (PAI) project',
  favicon: 'img/favicon.ico',

  url: 'https://pai-autodocs.vercel.app',
  baseUrl: '/',

  organizationName: 'virtualian',
  projectName: 'pai-autodocs',

  trailingSlash: true,
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    format: 'detect',
    mermaid: true,
  },

  themes: [
    '@docusaurus/theme-mermaid',
    [
      '@easyops-cn/docusaurus-search-local',
      /** @type {import("@easyops-cn/docusaurus-search-local").PluginOptions} */
      ({
        hashed: true,
        docsRouteBasePath: '/',
        indexBlog: false,
      }),
    ],
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
          editUrl: 'https://github.com/virtualian/pai-autodocs/tree/main/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      announcementBar: {
        id: 'pai_attribution',
        content:
          '\u25C6 <strong><a href="https://github.com/danielmiessler">Daniel Miessler</a></strong>\'s <a href="https://github.com/danielmiessler/Personal_AI_Infrastructure">Personal AI Infrastructure</a> \u2014 Unofficial, AI-generated docs \u00b7 <a href="/about">About this site</a>',
        backgroundColor: 'var(--ifm-color-primary-darkest)',
        textColor: 'var(--ifm-color-primary-lightest)',
        isCloseable: false,
      },
      metadata: [
        {
          name: 'og:title',
          content: 'Personal AI Infrastructure \u2014 Auto-Generated Documentation',
        },
        {
          name: 'og:description',
          content: 'Unofficial, AI-generated documentation for Daniel Miessler\'s Personal AI Infrastructure (PAI). Structured with Diataxis for users, developers, and contributors.',
        },
      ],
      navbar: {
        title: 'Home',
        items: [
          {
            type: 'doc',
            docId: 'user/overview',
            position: 'left',
            label: 'Start here',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [],
        copyright: `<a href="https://github.com/danielmiessler/Personal_AI_Infrastructure" class="pai-version-badge">PAI v4.0.3</a> &nbsp; <a href="https://github.com/danielmiessler/Personal_AI_Infrastructure">Personal AI Infrastructure</a> is created by <strong><a href="https://github.com/danielmiessler">Daniel Miessler</a></strong>. Docs generated by <a href="https://claude.ai">Claude</a> | Structured with <a href="https://diataxis.fr/">Diataxis</a> | <a href="https://github.com/virtualian/pai-autodocs">Repository</a> created by <a href="https://github.com/virtualian">@virtualian</a><br/><small><a href="/developer/algorithm">PAI Algorithm</a> v3.7.0 &middot; Site v1.1.0 | <a href="/changelog">Changelog</a></small>`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
      mermaid: {
        theme: {
          dark: 'neutral',
          light: 'neutral',
        },
        options: {
          themeVariables: {
            primaryColor: '#60A5FA',
            primaryTextColor: '#1e293b',
            primaryBorderColor: '#93c5fd',
            lineColor: '#64748b',
            secondaryColor: '#e0f2fe',
            tertiaryColor: '#f0f9ff',
            fontFamily: 'system-ui, sans-serif',
          },
        },
      },
      colorMode: {
        defaultMode: 'dark',
        respectPrefersColorScheme: true,
      },
    }),

};

export default config;
